FROM python:3.12-slim

WORKDIR /mlflow

RUN pip install --upgrade pip && \
    pip install --no-cache-dir mlflow==2.14.3 setuptools==68.2.2

RUN mkdir -p /mlflow/artifacts

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--serve-artifacts"]
